### ISSUE TITLE
Erro após instalação.

### ISSUE THREAD

**Issue by raulrabelo** [deivisonarthur/OSC-Magento-Brasil#146]
Olá.

Após fazer a instalação estou recebendo a seguinte mensagem de erro tanto no bacjend como no frontend.

Error in file: "/home/mulhernaweb/public_html/newstore/app/code/community/Inovarti/Onestepcheckout/sql/onestepcheckout_setup/mysql4-install-2.0.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-ie' for key 'UNQ_MG_EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE'

Trace:
#0 /home/mulhernaweb/public_html/newstore/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /home/mulhernaweb/public_html/newstore/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.0.2')
#2 /home/mulhernaweb/public_html/newstore/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.0.2')
#3 /home/mulhernaweb/public_html/newstore/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/mulhernaweb/public_html/newstore/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/mulhernaweb/public_html/newstore/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /home/mulhernaweb/public_html/newstore/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/mulhernaweb/public_html/newstore/index.php(87): Mage::run('', 'store')
#8 {main}

O que pode ser?
Abraços

**Comment by rafaelstz** [comment]
Que módulos você já tinha instalado?
