### ISSUE TITLE
Incompatibilidade OneStepCkeckout Free

### ISSUE THREAD

**Issue by grfbr** [deivisonarthur/OSC-Magento-Brasil#79]
Salve pessoal, tudo bem?

Eu já possuo o OneStepCkeckout instalado em minha loja, porem o modulo da RedeCard do  Alex Braga não funciona neste módulo.

Eu tentei colocar os arquivos por cima e tentar re-configurar, porem quando eu tento salvar as configurações no administrador, aparece o erro 404.

Gostaria de saber se alguém consegue me dar uma luz... 

Abraços.

**Comment by deivisonarthur** [comment]
Brother ao ver o erro 404 saia da adm e entre novamente

Enviado via iPhone

Em 10/06/2013, às 16:15, Fernando notifications@github.com escreveu:

**Comment by grfbr** [comment]
Já tentei, porem acontece a mesma coisa..

**Comment by grfbr** [comment]
Na verdade, agora funcionou, porem quando tento fazer alguma ação no carrinho acontece isso:

Warning: include_once(/home/Clientes/loja/www/lib/MaxMind/GeoIP/geoip.inc): failed to open stream: No such file or directory  in /home/Clientes/loja/www/app/code/local/DeivisonArthur/OnepageCheckout/Model/Type/Geo.php on line 3

#0 /home/Clientes/loja/www/app/code/local/DeivisonArthur/OnepageCheckout/Model/Type/Geo.php(3): mageCoreErrorHandler(2, 'include_once(/h...', '/home/Clientes/...', 3, Array)
#1 /home/Clientes/loja/www/app/code/local/DeivisonArthur/OnepageCheckout/Model/Type/Geo.php(3): include_once()
#2 /home/Clientes/loja/www/lib/Varien/Autoload.php(93): include('/home/Clientes/...')
#3 [internal function]: Varien_Autoload->autoload('DeivisonArthur_...')
#4 [internal function]: spl_autoload_call('DeivisonArthur_...')
#5 /home/Clientes/loja/www/app/code/core/Mage/Core/Model/Config.php(1346): class_exists('DeivisonArthur_...')
#6 /home/Clientes/loja/www/app/Mage.php(462): Mage_Core_Model_Config->getModelInstance('onepagecheckout...', Array)
#7 /home/Clientes/loja/www/app/Mage.php(476): Mage::getModel('onepagecheckout...', Array)
#8 /home/Clientes/loja/www/app/code/local/DeivisonArthur/OnepageCheckout/controllers/IndexController.php(88): Mage::getSingleton('onepagecheckout...')
#9 /home/Clientes/loja/www/app/code/local/DeivisonArthur/OnepageCheckout/controllers/IndexController.php(100): DeivisonArthur_OnepageCheckout_IndexController->getOnepagecheckout()
#10 /home/Clientes/loja/www/app/code/core/Mage/Core/Controller/Varien/Action.php(419): DeivisonArthur_OnepageCheckout_IndexController->indexAction()
#11 /home/Clientes/loja/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 /home/Clientes/loja/www/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /home/Clientes/loja/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /home/Clientes/loja/www/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#15 /home/Clientes/loja/www/index.php(88): Mage::run('', 'store')
#16 {main}
